version: '3'

services:
  mis-nginx:
    container_name: mis-nginx
    build: .
    image: mis-nginx
    restart: always
    ports:
      - 8080:80

  mis-frontend:
    container_name: mis-frontend
    build: mis-frontend
    image: mis-frontend
    restart: always

  mis-backend:
    container_name: mis-backend
    build: mis-backend
    image: mis-backend
    restart: always
    environment:
      ENABLE_AUTORELOAD: 'False'
      ENABLE_DEVELOP_MOD: 'False'
      ENABLE_RANDOM_JWT_SECRET: 'True'
      POSTGRES_DSN: 'postgresql://root:example@mis-postgres:5432/mis'
    volumes:
      - /opt/mis/files:/api/files

  mis-postgres:
    container_name: mis-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mis
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    volumes:
      - /opt/mis/postgresql:/var/lib/postgresql/data
